### PR TITLE
Refactor comment body

### PR DESCRIPTION
**Pull request by Serabe**
Refactor the body of the comment to use a couple of helpers instead of a long
list of `if`s in the html.

This will need an adjustment after merging #643

### CODE REVIEW

**Comment by Serabe** [comment]
For failing tests, see #643.

For coverage decreasing, I see you are not covering helper methods for comments. Shall I add a spec for them?

**Comment by Serabe** [comment]
Fix the issue after merging #643

**Comment by voodoorai2000** [comment]
Thank you @Serabe! Yes please, those helper specs would be great!

**Comment by Serabe** [comment]
Done. I should start doing these things earlier...

**Comment by xuanxu** [comment]
ole!

**Pull request merged**
